ITL-1
UltraMKF12/Internship-TodoApp pull request #1
Opened 2024-03-12 14:35 UTC by UltraMKF12

2024-03-12 15:00 UTC, zsolt-wbg requested changes

2024-03-12 15:00 UTC, zsolt-wbg commented on src/App.vue
> +import TodoHeader from './components/TodoHeader.vue'
Please add this code block in tsconfig.json in order to use import paths with '@/...' 
`"paths": {
            "@/*": [
                "src/*"
            ]
        },`

2024-03-12 15:00 UTC, zsolt-wbg commented on src/App.vue
> +<script setup lang="ts">
The order in a vue document should be: <template>, <script> and <style>

2024-03-12 15:00 UTC, zsolt-wbg commented on src/components/TodoHeader.vue
> +<script setup lang="ts">
Same here

2024-03-12 15:00 UTC, zsolt-wbg commented on src/components/TodoHeader.vue
> +    <button @click="$emit('addTodo')">
Create Base button component if you intend to use it more than one time.

2024-03-12 15:00 UTC, zsolt-wbg commented on src/components/icons/plus_icon.vue
> +<template>
Please name vue components with PascalCase and ts files with kebab-case

2024-03-12 15:00 UTC, zsolt-wbg commented on src/components/icons/plus_icon.vue
> +  <svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
Please add HeroIcons to the project in order to use icons via the projects
https://heroicons.com/

2024-03-12 15:45 UTC, szabolcs3 requested changes

2024-03-12 15:45 UTC, szabolcs3 commented on src/components/icons/PlusIcon.vue
> +<template>
You can delete this file.

2024-03-12 15:45 UTC, szabolcs3 commented on src/components/TodoHeader.vue
> +    <BaseButton>
You don't need to wrap around the icon with button

2024-03-12 15:45 UTC, szabolcs3 commented on src/components/BaseButton.vue
> +  <slot></slot>
Please use `<button>` html tag here and add some attributes to it so you can easily change the button attributes.
```
Example: 

- Props (label, disabled, text color, background color, button text)
- Emits (click)
 ```

2024-03-13 08:13 UTC, zsolt-wbg requested changes

2024-03-13 08:13 UTC, zsolt-wbg commented on src/components/TodoHeader.vue
> +    <PlusCircleIcon @click="$emit('addTodo')" class="h-16 w-16 text-green-400 cursor-pointer" />
Please use the correct attribute order! Here is an example: https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/attributes-order.md
But we will send you the "Vue Bible" :)

2024-03-13 08:13 UTC, zsolt-wbg commented on src/components/TodoHeader.vue
> +    <PlusCircleIcon @click="$emit('addTodo')" class="h-16 w-16 text-green-400 cursor-pointer" />
Please use a separate function for emit, for instance:
`@click="addTodo"`
`function addTodo() {
   emit('addTodo')
}`

2024-03-13 08:13 UTC, zsolt-wbg commented on src/components/BaseButton.vue
> +interface Props {
Please add the props directly to the button element tag, like this:
```
<button
   :label="label"
   :disabled="disabled"
   :class="[textColor, backgroundColor]"
>
      { buttonText }
</button>
```

2024-03-13 09:12 UTC, szabolcs3 approved these changes

2024-03-13 09:13 UTC, zsolt-wbg approved these changes

2024-03-13 09:19 UTC, merged